import { useState, type FormEvent, type ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { settingsApi, servicesApi } from "@/api/resources";
import { useBusiness } from "@/hooks/useAppData";
import { Button } from "@/components/Button";
import { Input } from "@/components/Input";
import { ApiError } from "@/api/client";

const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export function OnboardingPage() {
  const navigate = useNavigate(); const { data: business } = useBusiness();
  const [step, setStep] = useState(0); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const [service, setService] = useState({ name: "", category: "", price: "", durationMinutes: "60" });
  const [hours, setHours] = useState(() => DAYS.map((_, dayOfWeek) => ({ dayOfWeek, openTime: "09:00", closeTime: "17:00", isClosed: dayOfWeek === 0 })));
  const [profile, setProfile] = useState({ name: business?.name ?? "", phone: business?.phone ?? "", email: business?.email ?? "", address: business?.address ?? "", timezone: business?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone });
  async function run(action: () => Promise<void>) { setError(null); setSaving(true); try { await action(); } catch (e) { setError(e instanceof ApiError ? e.message : "We couldn't save that. Please try again."); } finally { setSaving(false); } }
  return <div className="mx-auto max-w-2xl p-4 sm:p-8"><p className="text-sm font-medium text-brass-600">Set up SalonFlow</p><h1 className="mt-1 font-display text-3xl text-ink">Let’s get your salon ready</h1><p className="mt-2 text-sm text-ink-muted">Step {step + 1} of 4 — you can update this later in Settings.</p><div className="mt-6 h-1 overflow-hidden rounded bg-paper-sunken"><div className="h-full bg-brass-500" style={{ width: `${(step + 1) * 25}%` }} /></div><div className="mt-8 rounded-lg border border-line bg-paper-raised p-5 shadow-card sm:p-7">
    {step === 0 && <form className="space-y-4" onSubmit={e => { e.preventDefault(); run(async () => { await settingsApi.update(profile); setStep(1); }); }}><h2 className="font-display text-xl">Business details</h2><Field label="Business name"><Input required value={profile.name} onChange={e => setProfile({ ...profile, name: e.target.value })} /></Field><Field label="Phone"><Input required value={profile.phone} onChange={e => setProfile({ ...profile, phone: e.target.value })} /></Field><Field label="Business email"><Input type="email" value={profile.email} onChange={e => setProfile({ ...profile, email: e.target.value })} /></Field><Field label="Address"><Input value={profile.address} onChange={e => setProfile({ ...profile, address: e.target.value })} /></Field><Field label="Timezone"><Input required value={profile.timezone} onChange={e => setProfile({ ...profile, timezone: e.target.value })} /></Field><Footer error={error}><Button type="submit" loading={saving}>Continue</Button></Footer></form>}
    {step === 1 && <form className="space-y-4" onSubmit={e => { e.preventDefault(); run(async () => { if (service.name.trim()) await servicesApi.create({ ...service, name: service.name.trim(), price: Number(service.price), durationMinutes: Number(service.durationMinutes) }); setStep(2); }); }}><h2 className="font-display text-xl">Add your first service</h2><p className="text-sm text-ink-muted">You can add more services from the Services page.</p><Field label="Service name"><Input value={service.name} onChange={e => setService({ ...service, name: e.target.value })} /></Field><Field label="Category"><Input value={service.category} onChange={e => setService({ ...service, category: e.target.value })} /></Field><div className="grid grid-cols-2 gap-4"><Field label="Price"><Input type="number" min="0" value={service.price} onChange={e => setService({ ...service, price: e.target.value })} /></Field><Field label="Duration (minutes)"><Input type="number" min="1" value={service.durationMinutes} onChange={e => setService({ ...service, durationMinutes: e.target.value })} /></Field></div><Footer error={error}><Button variant="secondary" type="button" onClick={() => setStep(2)}>Skip</Button><Button type="submit" loading={saving}>Continue</Button></Footer></form>}
    {step === 2 && <form className="space-y-3" onSubmit={e => { e.preventDefault(); run(async () => { await settingsApi.setWorkingHours(hours); setStep(3); }); }}><h2 className="font-display text-xl">Business hours</h2>{hours.map((day, index) => <div className="grid grid-cols-[1fr_auto_auto] items-center gap-2 text-sm" key={day.dayOfWeek}><label><input type="checkbox" checked={!day.isClosed} onChange={e => setHours(hours.map((item, i) => i === index ? { ...item, isClosed: !e.target.checked } : item))} className="mr-2 accent-brass-500" />{DAYS[index]}</label><Input aria-label={`${DAYS[index]} opens`} disabled={day.isClosed} type="time" value={day.openTime} onChange={e => setHours(hours.map((item, i) => i === index ? { ...item, openTime: e.target.value } : item))} /><Input aria-label={`${DAYS[index]} closes`} disabled={day.isClosed} type="time" value={day.closeTime} onChange={e => setHours(hours.map((item, i) => i === index ? { ...item, closeTime: e.target.value } : item))} /></div>)}<Footer error={error}><Button type="submit" loading={saving}>Continue</Button></Footer></form>}
    {step === 3 && <div className="space-y-5"><h2 className="font-display text-xl">You’re ready to go</h2><p className="text-sm text-ink-muted">Invite managers or staff from Settings whenever you’re ready. Connected channels always use official authorization flows.</p><Button onClick={() => navigate("/", { replace: true })}>Go to your dashboard</Button></div>}
  </div></div>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm font-medium text-ink-soft"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function Footer({ error, children }: { error: string | null; children: ReactNode }) { return <div className="flex items-center justify-between gap-3 pt-2">{error ? <p role="alert" className="text-sm text-danger">{error}</p> : <span />}{children}</div>; }
