import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { onboardingApi, settingsApi, teamApi } from "@/api/resources";
import { useBusiness } from "@/hooks/useAppData";
import { Button } from "@/components/Button";
import { Input } from "@/components/Input";
import { SettingsWorkingHours } from "@/components/settings/SettingsWorkingHours";
import { Card } from "@/components/Card";

const labels: Record<string, string> = { BUSINESS_DETAILS: "Business details", SERVICES: "Services", BUSINESS_HOURS: "Business hours", TEAM: "Team", INTEGRATIONS: "Integrations", REVIEW: "Review" };

export function OnboardingPage() {
  const navigate = useNavigate(); const { data: business, refetch } = useBusiness();
  const [state, setState] = useState<any>(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [service, setService] = useState({ name: "", price: "", durationMinutes: "60" }); const [team, setTeam] = useState({ name: "", email: "", password: "", role: "STAFF" as "STAFF" | "MANAGER" });
  const load = async () => setState(await onboardingApi.state());
  if (!state) { void load(); return <div className="p-8 text-sm text-ink-muted">Loading setup…</div>; }
  const run = async (task: () => Promise<unknown>) => { setSaving(true); setError(""); try { await task(); await refetch(); await load(); } catch (e: any) { setError(e.message ?? "We couldn't save that. Please try again."); } finally { setSaving(false); } };
  const step = state.onboardingStep; const profile = { name: business?.name ?? "", phone: business?.phone ?? "", timezone: business?.timezone ?? "Africa/Lagos" };
  const stepNumber = ["BUSINESS_DETAILS", "SERVICES", "BUSINESS_HOURS", "TEAM", "INTEGRATIONS", "REVIEW"].indexOf(step) + 1;
  return <div className="min-h-screen bg-workspace"><div className="mx-auto max-w-2xl p-4 sm:p-8"><p className="text-sm font-medium text-brass-600">Set up SalonFlow</p><h1 className="mt-1 font-display text-3xl text-ink">Let’s get your salon ready</h1><p className="mt-2 text-sm text-ink-muted">Step {stepNumber} of 6 · Your progress is saved as you go.</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-paper-sunken"><div className="h-full bg-brass-500 transition-[width]" style={{ width: `${(stepNumber / 6) * 100}%` }} /></div><Card className="mt-6 p-5 sm:p-7"><h2 className="font-display text-xl">{labels[step]}</h2>{error && <p className="mt-3 text-sm text-danger">{error}</p>}
    {step === "BUSINESS_DETAILS" && <StepForm initial={profile} saving={saving} onSubmit={(data: { name: string; phone: string; timezone: string }) => run(async () => { await settingsApi.update(data); await onboardingApi.advance(); })} />}
    {step === "SERVICES" && <form className="mt-4 space-y-3" onSubmit={e => { e.preventDefault(); run(async () => { await onboardingApi.createService({ name: service.name, price: Number(service.price), durationMinutes: Number(service.durationMinutes) }); await onboardingApi.advance(); }); }}><p className="text-sm text-ink-muted">Add one active service to start taking bookings.</p><Input required placeholder="Service name" value={service.name} onChange={e => setService({ ...service, name: e.target.value })}/><Input required min="0" type="number" placeholder="Price" value={service.price} onChange={e => setService({ ...service, price: e.target.value })}/><Input required min="1" type="number" value={service.durationMinutes} onChange={e => setService({ ...service, durationMinutes: e.target.value })}/><Button loading={saving}>Save service and continue</Button></form>}
    {step === "BUSINESS_HOURS" && <SettingsWorkingHours onSave={(hours) => run(() => onboardingApi.saveBusinessHours(hours))} />}
    {step === "TEAM" && <form className="mt-4 space-y-3" onSubmit={e => { e.preventDefault(); run(async () => { await teamApi.invite(team); await onboardingApi.advance(); }); }}><p className="text-sm text-ink-muted">Optional login accounts; these are not bookable Staff profiles.</p><Input required placeholder="Name" value={team.name} onChange={e => setTeam({ ...team, name: e.target.value })}/><Input required type="email" placeholder="Email" value={team.email} onChange={e => setTeam({ ...team, email: e.target.value })}/><Input required type="password" placeholder="Temporary password" value={team.password} onChange={e => setTeam({ ...team, password: e.target.value })}/><Button type="button" variant="secondary" onClick={() => run(onboardingApi.skip)}>Skip for now</Button><Button className="ml-2" loading={saving}>Add team account</Button></form>}
    {step === "INTEGRATIONS" && <StepNotice text="WhatsApp and Instagram can be connected later from Settings. They are optional." saving={saving} onClick={() => run(onboardingApi.skip)} />}
    {step === "REVIEW" && <Review saving={saving} onComplete={() => run(async () => { await onboardingApi.complete(); navigate("/", { replace: true }); })}/>}</Card></div></div>;
}
function StepForm({ initial, saving, onSubmit }: any) { const [data, setData] = useState(initial); return <form className="mt-4 space-y-3" onSubmit={e => { e.preventDefault(); onSubmit(data); }}><Input required value={data.name} onChange={e => setData({ ...data, name: e.target.value })}/><Input required value={data.phone} onChange={e => setData({ ...data, phone: e.target.value })}/><Input required value={data.timezone} onChange={e => setData({ ...data, timezone: e.target.value })}/><Button loading={saving}>Continue</Button></form>; }
function StepNotice({ text, saving, onClick }: any) { return <div className="mt-4"><p className="text-sm text-ink-muted">{text}</p><Button className="mt-4" loading={saving} onClick={onClick}>Continue</Button></div>; }
function Review({ saving, onComplete }: any) { const [review, setReview] = useState<any>(); if (!review) { void onboardingApi.review().then(setReview); return <p className="mt-4 text-sm text-ink-muted">Loading review…</p>; } return <div className="mt-4 space-y-3 text-sm"><p>{review.business.name} · {review.business.timezone}</p><p>{review.activeServiceCount} active service(s), {review.teamAccountCount} team account(s)</p><Button loading={saving} onClick={onComplete}>Finish setup</Button></div>; }
