jest.mock("../../../lib/prisma");
import { prisma } from "../../../lib/prisma";
import { finalizeScheduledCancellation, scheduleCancellation, undoScheduledCancellation } from "../billingService";
import { reconcileKnownSubscription } from "../billingService";
import { resolveBusinessAccess } from "../../subscriptions/subscriptionService";

const active = { id: "sub", businessId: "biz", planCode: "STARTER" as const, status: "ACTIVE" as const, provider: null, providerCustomerId: null, providerSubscriptionId: null, providerPlanCode: null, trialEndsAt: null, graceEndsAt: null, currentPeriodEndsAt: new Date("2026-10-10"), cancelAtPeriodEnd: false, createdAt: new Date(), updatedAt: new Date() };
beforeEach(() => { jest.clearAllMocks(); (prisma.auditLog.create as jest.Mock).mockResolvedValue({}); (prisma.subscription.update as jest.Mock).mockResolvedValue({ ...active, cancelAtPeriodEnd: true }); });
describe("billing cancellation", () => {
  it("schedules once and keeps access before period end", async () => { (prisma.subscription.findUnique as jest.Mock).mockResolvedValue(active); await scheduleCancellation("biz", "owner"); expect(resolveBusinessAccess({ ...active, cancelAtPeriodEnd: true }, new Date("2026-10-09"))).toMatchObject({ allowed: true }); });
  it("is idempotent when already scheduled", async () => { (prisma.subscription.findUnique as jest.Mock).mockResolvedValue({ ...active, cancelAtPeriodEnd: true }); await scheduleCancellation("biz", "owner"); expect(prisma.subscription.update).not.toHaveBeenCalled(); });
  it("finalizes only after a known period end and never for null", async () => { (prisma.subscription.findUnique as jest.Mock).mockResolvedValue({ ...active, cancelAtPeriodEnd: true }); await finalizeScheduledCancellation("biz", new Date("2026-10-11")); expect(prisma.subscription.update).toHaveBeenCalledWith(expect.objectContaining({ data: { status: "CANCELLED" } })); jest.clearAllMocks(); (prisma.subscription.findUnique as jest.Mock).mockResolvedValue({ ...active, currentPeriodEndsAt: null, cancelAtPeriodEnd: true }); await finalizeScheduledCancellation("biz", new Date("2026-10-11")); expect(prisma.subscription.update).not.toHaveBeenCalled(); });
  it("undoes only before cancellation is effective", async () => { (prisma.subscription.findUnique as jest.Mock).mockResolvedValue({ ...active, cancelAtPeriodEnd: true }); await undoScheduledCancellation("biz", "owner"); expect(prisma.subscription.update).toHaveBeenCalledWith(expect.objectContaining({ data: { cancelAtPeriodEnd: false } })); });
  it("rejects undo after cancellation is effective without resurrection", async () => { (prisma.subscription.findUnique as jest.Mock).mockResolvedValue({ ...active, status: "CANCELLED", cancelAtPeriodEnd: true, currentPeriodEndsAt: new Date("2020-10-01") }); await expect(undoScheduledCancellation("biz", "owner")).rejects.toThrow(); expect(prisma.subscription.update).not.toHaveBeenCalled(); });
  it("reconciles only a known provider subscription once", async () => { const known = { ...active, provider: "PAYSTACK", providerSubscriptionId: "provider-sub", providerCustomerId: null, providerPlanCode: null }; (prisma.subscription.findUnique as jest.Mock).mockResolvedValue(known); const provider = { getSubscriptionState: jest.fn().mockResolvedValue({ providerSubscriptionId: "provider-sub", providerCustomerId: "customer", providerPlanCode: "plan", currentPeriodEndsAt: new Date("2026-11-01") }) } as any; await expect(reconcileKnownSubscription("biz", provider)).resolves.toMatchObject({ reconciled: true, changed: true }); expect(prisma.subscription.update).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "sub" }, data: expect.objectContaining({ providerCustomerId: "customer" }) })); });
  it("does not mutate unmatched or ambiguous provider reconciliation", async () => { (prisma.subscription.findUnique as jest.Mock).mockResolvedValue({ ...active, providerSubscriptionId: "provider-sub" }); const provider = { getSubscriptionState: jest.fn().mockResolvedValue({ providerSubscriptionId: "other" }) } as any; await expect(reconcileKnownSubscription("biz", provider)).resolves.toMatchObject({ reconciled: false }); expect(prisma.subscription.update).not.toHaveBeenCalled(); });
});
